name: MovsChallenge

options:
  bundleIdPrefix: adrianalmeida
  deploymentTarget:
    iOS: "15.2"

configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Configs/Base.xcconfig
  Release: Configs/Base.xcconfig

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.0.0
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    from: 1.0.0

targets:
  MovsChallenge:
    type: application
    platform: iOS
    info:
      path: MovsChallenge/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
    configFiles:
      Debug: Configs/AppDebug.xcconfig
      Release: Configs/AppRelease.xcconfig
    sources: MovsChallenge
    dependencies:
      - package: SnapKit
    preBuildScripts:
      - path: Scripts/SwiftLint.sh
        name: SwiftLint

  MovsChallengeTests:
    type: bundle.unit-test
    platform: iOS
    configFiles:
      Debug: Configs/AppTests.xcconfig
    sources: MovsChallengeTests
    dependencies:
      - target: MovsChallenge
      - package: SnapshotTesting

  MovsChallengeUITests:
    type: bundle.ui-testing
    platform: iOS
    configFiles:
      Debug: Configs/AppUITests.xcconfig
    sources: MovsChallengeUITests
    dependencies:
      - target: MovsChallenge

schemes:
  MovsChallenge:
    build:
      targets:
        MovsChallenge: all
        MovsChallengeTests: [test]
        MovsChallengeUITests: [test]
    run:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - MovsChallenge
      targets:
        - name: MovsChallengeTests
          randomExecutionOrder: true
        - name: MovsChallengeUITests
          randomExecutionOrder: true
